import Footer from '@/app/components/common/footer'
import Header from '@/app/components/common/header'

export const metadata = {
  title: 'Next.js sdasdasdsa',
  deScription: 'Generated by Next.js adasdasdas',
}

export default function LayoutHome({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Header></Header>
        {children}
      <Footer></Footer>
    </>
  )
}
